---
- hosts: ja3
  tasks:
      - include_role:
          name: letsencrypt_certs
        vars:
            domain: ja3.appianis.com
      - name: Install docker
        snap:
            name: docker
        become: yes

      - name: create the /etc/docker dir
        file:
            path: /etc/docker
            state: directory
            mode: '0755'
        become: yes

      - name: add docker daemon for DNS stuff
        copy: 
            src: ~/ja3-sig-gen/docker_daemon.json
            dest: /etc/docker/daemon.json
            owner: root
            group: root
            mode: '0644'
        become: yes
            
      - name: symlink for resolv.conf
        file:
            src: /run/systemd/resolve/resolv.conf
            dest: /etc/resolv.conf
            owner: root
            group: root
            state: link
        become: yes
